using System.Text;
using System.Text.Json;
using Daggeragent.Configuration;

namespace Daggeragent.Tools;

/// <summary>
/// Translates a list of <see cref="McpServerConfig"/> entries into the on-disk config
/// formats expected by Claude Code CLI (JSON) and Codex CLI (TOML), so a spawned CLI can
/// be handed the same MCP servers DaggerAgent has configured. Only servers with
/// <see cref="McpServerConfig.PassthroughToCli"/>=true should be passed in here — the
/// caller is responsible for filtering; this helper renders whatever it's given.
/// </summary>
internal static class CliMcpConfigBuilder
{
    private static readonly JsonSerializerOptions ClaudeJson = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
    };

    /// <summary>
    /// Claude CLI mcp config (--mcp-config &lt;file&gt;): JSON with <c>mcpServers</c> keyed by name.
    /// Each entry is either <c>{type:"http", url, headers?}</c> or <c>{type:"stdio", command, args?, env?}</c>.
    /// </summary>
    public static string BuildClaudeConfig(IEnumerable<McpServerConfig> servers)
    {
        var mcp = new Dictionary<string, object>();
        foreach (var s in servers)
        {
            if (string.IsNullOrWhiteSpace(s.Name)) continue;
            if (!string.IsNullOrWhiteSpace(s.Url))
            {
                var entry = new Dictionary<string, object?>
                {
                    ["type"] = "http",
                    ["url"] = s.Url,
                };
                if (!string.IsNullOrWhiteSpace(s.AuthHeader))
                    entry["headers"] = new Dictionary<string, string> { ["Authorization"] = s.AuthHeader };
                mcp[s.Name] = entry;
            }
            else if (!string.IsNullOrWhiteSpace(s.Command))
            {
                var entry = new Dictionary<string, object?>
                {
                    ["type"] = "stdio",
                    ["command"] = s.Command,
                };
                if (s.Arguments.Count > 0) entry["args"] = s.Arguments;
                if (s.EnvironmentVariables.Count > 0) entry["env"] = s.EnvironmentVariables;
                mcp[s.Name] = entry;
            }
            // else: misconfigured server — skip
        }
        return JsonSerializer.Serialize(new { mcpServers = mcp }, ClaudeJson);
    }

    /// <summary>
    /// Codex CLI config.toml: <c>[mcp_servers.&lt;name&gt;]</c> sections. As of writing, Codex's
    /// MCP support is stdio-only via its config file — HTTP servers are skipped with a comment
    /// so the file is still valid TOML and the user has a breadcrumb if a server is missing.
    /// Write to <c>&lt;CODEX_HOME&gt;/config.toml</c>.
    /// </summary>
    public static string BuildCodexConfig(IEnumerable<McpServerConfig> servers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by DaggerAgent for delegate_to_codex. Do not edit.");
        sb.AppendLine();

        foreach (var s in servers)
        {
            if (string.IsNullOrWhiteSpace(s.Name)) continue;

            if (!string.IsNullOrWhiteSpace(s.Url) && string.IsNullOrWhiteSpace(s.Command))
            {
                sb.Append("# Skipped MCP server '").Append(s.Name)
                  .AppendLine("' — HTTP MCP servers aren't supported by the Codex CLI config; only stdio.");
                sb.AppendLine();
                continue;
            }
            if (string.IsNullOrWhiteSpace(s.Command)) continue;

            sb.Append("[mcp_servers.").Append(s.Name).AppendLine("]");
            sb.Append("command = ").AppendLine(TomlString(s.Command));
            if (s.Arguments.Count > 0)
            {
                sb.Append("args = [");
                for (int i = 0; i < s.Arguments.Count; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append(TomlString(s.Arguments[i]));
                }
                sb.AppendLine("]");
            }
            if (s.EnvironmentVariables.Count > 0)
            {
                sb.Append("env = { ");
                int n = 0;
                foreach (var (k, v) in s.EnvironmentVariables)
                {
                    if (n++ > 0) sb.Append(", ");
                    // TOML bare keys: a-z A-Z 0-9 _ -; anything else needs quoting.
                    var key = IsBareTomlKey(k) ? k : TomlString(k);
                    sb.Append(key).Append(" = ").Append(TomlString(v));
                }
                sb.AppendLine(" }");
            }
            sb.AppendLine();
        }
        return sb.ToString();
    }

    private static string TomlString(string s)
    {
        // TOML basic-string escaping: \\, \", \n, \r, \t.
        var sb = new StringBuilder(s.Length + 4);
        sb.Append('"');
        foreach (var c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 0x20) sb.Append("\\u").Append(((int)c).ToString("X4"));
                    else sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private static bool IsBareTomlKey(string k)
    {
        if (string.IsNullOrEmpty(k)) return false;
        foreach (var c in k)
        {
            if (!(char.IsLetterOrDigit(c) || c == '_' || c == '-')) return false;
        }
        return true;
    }
}
